# A Workflow for adjusting the version number of the next release

name: Set next version
run-name: Set next version (${{ inputs.part }})

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Part to increment: Major, Minor, Patch or the next release, e.g. 1.2.3"
        required: true
        default: Minor

permissions:
  contents: read

concurrency: "${{ github.repository }}-versioning"

jobs:
  version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
      - name: Fetch version history
        run: git fetch --tags --unshallow
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3.3.2
        with:
          gradle-home-cache-cleanup: true
      - name: Increment version
        if: contains(fromJson('["Major", "Minor", "Patch"]'), github.event.inputs.part)
        run: |
          # The following command will trigger the build.yml workflow as it pushes a alpha tag
          ./gradlew markNextVersion -Prelease.incrementer=increment${{ github.event.inputs.part }}
      - name: Set next version
        if: (!contains(fromJson('["Major", "Minor", "Patch"]'), github.event.inputs.part))
        run: |
          # The following command will trigger the build.yml workflow as it pushes a alpha tag
          ./gradlew markNextVersion -Prelease.version=${{ github.event.inputs.part }}
